import { todayInSaoPaulo, formatTransactionDate } from './finance-date.mjs';
import { readCreditCardPdf, fileSha256 } from './credit-card-import.js?v=2';
const $ = selector => document.querySelector(selector);
const section = $('#credit-card-section');
const forms = { group: $('#card-group-form'), period: $('#card-period-form'), transaction: $('#card-transaction-form'), import: $('#card-import-form') };
const months = ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const money = value => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
let data = null, busy = false, requestId = crypto.randomUUID(), editingGroup = null, editingPeriod = null, editingTransaction = null, importRows = [], importFile = null;
function status(text,error=false){ $('#card-status').textContent=text; $('#card-status').className=`save-status${error?' is-error':''}`; }
function view(name){ Object.entries(forms).forEach(([key,form])=>form.hidden=key!==name); $('#card-expenses').hidden=name!=='expenses'; document.querySelectorAll('[data-card-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.cardView===name))); }
function cardArea(show){ section.hidden=!show; $('#admin-form').hidden=show; $('#finance-section').hidden=true; $('#show-credit-card').setAttribute('aria-pressed',String(show)); if(show){$('#show-content').setAttribute('aria-pressed','false');$('#show-finance').setAttribute('aria-pressed','false');} if(show&&!data) request(); }
function controls(){ section.querySelectorAll('button,input,select').forEach(control=>control.disabled=busy||!data); const noGroups=!data?.groups.length; forms.transaction.elements.groupId.disabled=busy||noGroups; forms.transaction.querySelector('[type=submit]').disabled=busy||noGroups; $('#card-refresh').disabled=busy; installmentFields(); }
function installmentFields(){ const term=forms.transaction.elements.payment.value==='2'; forms.transaction.querySelectorAll('[data-installment-field]').forEach(label=>{label.hidden=!term;label.querySelector('input').required=term;label.querySelector('input').disabled=!term||busy||!data;}); const f=forms.transaction.elements; $('#card-installment-summary').textContent=term&&f.currentInstallment.value&&f.installmentCount.value?`Serão gravadas as parcelas ${f.currentInstallment.value} a ${f.installmentCount.value}, uma por mês, incluindo a parcela atual.`:''; }
function color(index){return ['#c89b5b','#71b6aa','#879dd8','#bf8cc9','#d98772','#7ea666','#d5b66f','#7894a8'][index%8];}
function editButton(kind, record){const button=document.createElement('button');button.type='button';button.className='button button-secondary';button.textContent='Editar';button.dataset.cardEdit=kind;button.dataset.id=record.id;const description=kind==='group'?`grupo ${record.name}`:kind==='period'?`período ${months[record.month-1]} de ${record.year}`:`transação ${record.name}`;button.setAttribute('aria-label',`Editar ${description}`);return button;}
function deleteTransactionButton(record){const button=document.createElement('button');button.type='button';button.className='button button-danger';button.textContent='Excluir';button.dataset.cardDelete='transaction';button.dataset.id=record.id;button.setAttribute('aria-label',`Excluir transação ${record.name}`);return button;}
function renderLists(){
  $('#card-groups-list').replaceChildren();$('#card-groups-empty').hidden=data.groups.length>0;data.groups.forEach(group=>{const tr=document.createElement('tr');const name=document.createElement('td');name.textContent=group.name;const action=document.createElement('td');action.append(editButton('group',group));tr.append(name,action);$('#card-groups-list').append(tr);});
  $('#card-periods-list').replaceChildren();$('#card-periods-empty').hidden=data.periods.length>0;data.periods.forEach(period=>{const tr=document.createElement('tr');[`${months[period.month-1]} de ${period.year}`,formatTransactionDate(period.startDate),formatTransactionDate(period.endDate)].forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td);});const action=document.createElement('td');action.append(editButton('period',period));tr.append(action);$('#card-periods-list').append(tr);});
  $('#card-imports-list').replaceChildren();$('#card-imports-empty').hidden=(data.imports||[]).length>0;(data.imports||[]).forEach(item=>{const period=data.periods.find(p=>p.id===item.periodId);const tr=document.createElement('tr');[item.fileName,period?`${months[period.month-1]} de ${period.year}`:'Fatura removida',item.itemCount,new Date(item.createdAt).toLocaleString('pt-BR')].forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td);});$('#card-imports-list').append(tr);});
  $('#card-transactions-list').replaceChildren();$('#card-transactions-list-empty').hidden=data.transactions.length>0;data.transactions.forEach(item=>{const tr=document.createElement('tr');[new Date(item.createdAt).toLocaleString('pt-BR'),formatTransactionDate(item.purchaseDate||item.transactionDate),`${item.name}${item.isProjected?' · prevista':''}`,item.groupName,item.payment===1?'À VISTA':'À PRAZO',item.payment===1?'—':`${item.installmentNumber}/${item.installmentCount}`,money(item.value)].forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td);});const actions=document.createElement('td');actions.className='finance-row-actions';actions.append(editButton('transaction',item),deleteTransactionButton(item));tr.append(actions);$('#card-transactions-list').append(tr);});
}
function render(){
  renderLists();
  const groupSelection=forms.transaction.elements.groupId.value; forms.transaction.elements.groupId.replaceChildren(new Option(data.groups.length?'Selecione um grupo':'Cadastre um grupo primeiro','')); data.groups.forEach(group=>forms.transaction.elements.groupId.add(new Option(group.name,group.id))); forms.transaction.elements.groupId.value=groupSelection;
  const periodSelection=$('#card-period-filter').value; $('#card-period-filter').replaceChildren(new Option(data.periods.length?'Selecione uma fatura':'Nenhuma fatura cadastrada','')); data.periods.forEach(period=>$('#card-period-filter').add(new Option(`${months[period.month-1]} de ${period.year} · ${formatTransactionDate(period.startDate)} a ${formatTransactionDate(period.endDate)}`,period.id))); $('#card-period-filter').value=data.periods.some(p=>p.id===periodSelection)?periodSelection:(data.periods[0]?.id||''); renderExpenses(); controls();
  const importPeriod=forms.import.elements.periodId, selected=importPeriod.value;importPeriod.replaceChildren(new Option(data.periods.length?'Selecione uma fatura':'Cadastre um período primeiro',''));data.periods.forEach(period=>importPeriod.add(new Option(`${months[period.month-1]} de ${period.year} · ${formatTransactionDate(period.startDate)} a ${formatTransactionDate(period.endDate)}`,period.id)));importPeriod.value=data.periods.some(p=>p.id===selected)?selected:(data.periods[0]?.id||'');
}
function renderExpenses(){ const periodId=$('#card-period-filter').value; const rows=data?.transactions.filter(item=>item.periodId===periodId)||[]; const totals=new Map(); rows.forEach(item=>totals.set(item.groupId,(totals.get(item.groupId)||0)+Math.round(item.value*100))); const total=[...totals.values()].reduce((a,b)=>a+b,0); $('#card-expenses-empty').hidden=rows.length>0&&total>0; $('#card-expenses-empty').textContent=!periodId?'Selecione uma fatura.':!rows.length?'Nenhuma transação se encaixa nas datas desta fatura.':'As transações desta fatura têm valor zero.'; $('#card-expenses-content').hidden=total===0; $('#card-transactions').replaceChildren(); let start=0;const segments=[];$('#card-pie-legend').replaceChildren(); [...totals.entries()].forEach(([id,cents],index)=>{const group=data.groups.find(g=>g.id===id);const pct=cents/total*100;segments.push(`${color(index)} ${start}% ${start+pct}%`);start+=pct;const li=document.createElement('li');const swatch=document.createElement('span');swatch.className='finance-pie-swatch';swatch.style.backgroundColor=color(index);swatch.setAttribute('aria-hidden','true');const label=document.createElement('span');label.textContent=group?.name||'Grupo';const amount=document.createElement('strong');amount.textContent=`${money(cents/100)} · ${pct.toLocaleString('pt-BR',{maximumFractionDigits:2})}%`;li.append(swatch,label,amount);$('#card-pie-legend').append(li);}); $('#card-pie').style.background=`conic-gradient(${segments.join(',')})`;$('#card-pie').setAttribute('aria-label',[...totals].map(([id,c])=>`${data.groups.find(g=>g.id===id)?.name}: ${money(c/100)}`).join('; '));rows.forEach(item=>{const tr=document.createElement('tr');[formatTransactionDate(item.purchaseDate||item.transactionDate),`${item.name}${item.isProjected?' · prevista':''}`,item.groupName,item.payment===1?'À VISTA':'À PRAZO',item.payment===1?'—':`${item.installmentNumber}/${item.installmentCount}`,money(item.value)].forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td);});$('#card-transactions').append(tr);}); }
async function request(action){if(busy)return false;busy=true;controls();status(action?'Salvando…':'Carregando…');try{const response=await fetch('/api/admin/credit-card',{method:action?'POST':'GET',cache:'no-store',headers:{'Content-Type':'application/json','x-admin-password':getStoredAdminPassword()},...(action?{body:JSON.stringify(action)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error);data=result;render();status(action?'Salvo com sucesso.':'Dados atualizados.');return true;}catch(error){status(error.message||'Não foi possível acessar Cartão de Crédito.',true);return false;}finally{busy=false;controls();}}
$('#show-credit-card').addEventListener('click',()=>cardArea(true));$('#show-content').addEventListener('click',()=>{section.hidden=true;$('#show-credit-card').setAttribute('aria-pressed','false');});$('#show-finance').addEventListener('click',()=>{section.hidden=true;$('#show-credit-card').setAttribute('aria-pressed','false');});document.querySelectorAll('[data-card-view]').forEach(button=>button.addEventListener('click',()=>view(button.dataset.cardView)));$('#card-refresh').addEventListener('click',()=>request());$('#card-period-filter').addEventListener('change',renderExpenses);forms.transaction.elements.payment.addEventListener('change',installmentFields);forms.transaction.addEventListener('input',installmentFields);
$('#logout-admin').addEventListener('click',()=>{data=null;section.hidden=true;$('#show-credit-card').setAttribute('aria-pressed','false');clearGroupEdit();clearPeriodEdit();clearTransactionEdit();clearImport();status('');});

function clearGroupEdit(){editingGroup=null;forms.group.reset();requestId=crypto.randomUUID();$('#card-group-title').textContent='Incluir grupo';$('#card-group-cancel').hidden=true;forms.group.querySelector('[type=submit]').textContent='Salvar grupo';}
function clearPeriodEdit(){editingPeriod=null;forms.period.reset();requestId=crypto.randomUUID();defaults();$('#card-period-title').textContent='Incluir período';$('#card-period-cancel').hidden=true;forms.period.querySelector('[type=submit]').textContent='Salvar período';}
function clearTransactionEdit(){editingTransaction=null;forms.transaction.reset();requestId=crypto.randomUUID();defaults();$('#card-transaction-title').textContent='Incluir transação';$('#card-transaction-cancel').hidden=true;forms.transaction.querySelector('[type=submit]').textContent='Salvar transação';}
$('#card-group-cancel').addEventListener('click',clearGroupEdit);$('#card-period-cancel').addEventListener('click',clearPeriodEdit);$('#card-transaction-cancel').addEventListener('click',clearTransactionEdit);
section.addEventListener('click',async event=>{const button=event.target.closest('[data-card-edit],[data-card-delete]');if(!button||busy||!data)return;if(button.dataset.cardDelete==='transaction'){const record=data.transactions.find(item=>item.id===button.dataset.id);if(!record||!confirm(`Excluir a transação “${record.name}”?`))return;if(await request({type:'transaction',operation:'delete',id:record.id,revision:record.revision})){if(editingTransaction?.id===record.id)clearTransactionEdit();view('transaction');}return;}if(button.dataset.cardEdit==='group'){const record=data.groups.find(item=>item.id===button.dataset.id);if(!record)return;editingGroup={...record};forms.group.elements.name.value=record.name;$('#card-group-title').textContent='Editar grupo';$('#card-group-cancel').hidden=false;forms.group.querySelector('[type=submit]').textContent='Salvar alterações';forms.group.elements.name.focus();}else if(button.dataset.cardEdit==='period'){const record=data.periods.find(item=>item.id===button.dataset.id);if(!record)return;editingPeriod={...record};const f=forms.period.elements;f.month.value=record.month;f.year.value=record.year;f.startDate.value=record.startDate;f.endDate.value=record.endDate;$('#card-period-title').textContent='Editar período';$('#card-period-cancel').hidden=false;forms.period.querySelector('[type=submit]').textContent='Salvar alterações';f.month.focus();}else{const record=data.transactions.find(item=>item.id===button.dataset.id);if(!record)return;editingTransaction={...record};const f=forms.transaction.elements;f.transactionDate.value=record.purchaseDate||record.transactionDate;f.name.value=record.name;f.value.value=record.value;f.groupId.value=record.groupId;f.payment.value=record.payment;f.currentInstallment.value=record.installmentNumber;f.installmentCount.value=record.installmentCount;installmentFields();$('#card-transaction-title').textContent='Editar transação';$('#card-transaction-cancel').hidden=false;forms.transaction.querySelector('[type=submit]').textContent='Salvar alterações';f.transactionDate.focus();}});
forms.group.addEventListener('submit',async event=>{event.preventDefault();if(await request({type:'group',operation:editingGroup?'update':'create',id:editingGroup?.id||requestId,revision:editingGroup?.revision,name:forms.group.elements.name.value})){clearGroupEdit();view('group');}});
forms.period.addEventListener('submit',async event=>{event.preventDefault();const f=forms.period.elements;if(await request({type:'period',operation:editingPeriod?'update':'create',id:editingPeriod?.id||requestId,revision:editingPeriod?.revision,month:Number(f.month.value),year:Number(f.year.value),startDate:f.startDate.value,endDate:f.endDate.value})){clearPeriodEdit();view('period');}});
forms.transaction.addEventListener('submit',async event=>{event.preventDefault();const f=forms.transaction.elements;if(await request({type:'transaction',operation:editingTransaction?'update':'create',id:editingTransaction?.id||requestId,revision:editingTransaction?.revision,transactionDate:f.transactionDate.value,name:f.name.value,value:Number(f.value.value),groupId:f.groupId.value,payment:Number(f.payment.value),currentInstallment:Number(f.currentInstallment.value),installmentCount:Number(f.installmentCount.value)})){clearTransactionEdit();view('transaction');}});

const importKey=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\bPARC\s*\d+\s*\/\s*\d+\b/ig,'').replace(/[^a-zA-Z0-9]/g,'').toLocaleLowerCase('pt-BR');
function suggestedGroup(item){const category=importKey(item.category);let group=data.groups.find(record=>importKey(record.name)===category);if(!group){const old=data.transactions.find(record=>importKey(record.name)===importKey(item.name));group=old&&data.groups.find(record=>record.id===old.groupId);}if(!group)group=data.groups.find(record=>['outro','outros'].includes(importKey(record.name)));return group?.id||'';}
function optionSelect(values,selected){const select=document.createElement('select');values.forEach(([label,value])=>select.add(new Option(label,value)));select.value=String(selected);return select;}
function renderImportPreview(){const body=$('#card-import-items');body.replaceChildren();$('#card-import-preview').hidden=!importRows.length;$('#card-import-empty').hidden=Boolean(importRows.length);$('#card-import-confirm').hidden=!importRows.some(item=>item.include&&!item.reason);$('#card-import-clear').hidden=!importRows.length;
  importRows.forEach((item,index)=>{const tr=document.createElement('tr');tr.dataset.index=index;
    const check=document.createElement('input');check.type='checkbox';check.checked=item.include&&!item.reason;check.disabled=Boolean(item.reason);check.setAttribute('aria-label',`Importar ${item.name}`);
    const date=document.createElement('input');date.type='date';date.value=item.purchaseDate;date.required=true;
    const name=document.createElement('input');name.type='text';name.maxLength=120;name.value=item.name;name.required=true;
    const value=document.createElement('input');value.type='number';value.min='.01';value.max='99999999.99';value.step='.01';value.value=item.value.toFixed(2);value.required=true;
    const group=optionSelect([['Selecione',''],...data.groups.map(record=>[record.name,record.id])],suggestedGroup(item));group.required=true;
    const payment=optionSelect([['À VISTA','1'],['À PRAZO','2']],item.payment);
    const current=document.createElement('input');current.type='number';current.min=1;current.max=999;current.value=item.currentInstallment;
    const count=document.createElement('input');count.type='number';count.min=1;count.max=999;count.value=item.installmentCount;
    const parcel=document.createElement('div');parcel.className='card-import-installments';parcel.append(current,document.createTextNode('/'),count);
    const confidence=document.createElement('span');confidence.className=`card-import-confidence${item.confidence<75?' is-low':''}`;confidence.textContent=item.reason||`${item.confidence}%`;
    const cells=[check,date,name,value,group,payment,parcel,confidence].map(control=>{const td=document.createElement('td');td.append(control);return td;});tr.append(...cells);body.append(tr);
    const toggleParcel=()=>{const term=payment.value==='2';current.disabled=count.disabled=!term;if(!term){current.value=count.value=1;}};payment.addEventListener('change',toggleParcel);toggleParcel();check.addEventListener('change',()=>{$('#card-import-confirm').hidden=!body.querySelector('input[type=checkbox]:checked');});
  });controls();
}
function clearImport(){importRows=[];importFile=null;forms.import.elements.statement.value='';$('#card-import-progress').hidden=true;$('#card-import-progress-bar').value=0;$('#card-import-progress-text').textContent='';renderImportPreview();}
$('#card-import-clear').addEventListener('click',clearImport);
$('#card-import-read').addEventListener('click',async()=>{const period=data.periods.find(item=>item.id===forms.import.elements.periodId.value),file=forms.import.elements.statement.files[0];if(!period){status('Selecione uma fatura de destino.',true);return;}if(!file){status('Selecione o PDF da fatura.',true);return;}busy=true;controls();$('#card-import-progress').hidden=false;$('#card-import-empty').hidden=true;try{importRows=await readCreditCardPdf(file,period.endDate,(value,text)=>{$('#card-import-progress-bar').value=value;$('#card-import-progress-text').textContent=text;});importFile=file;renderImportPreview();status(importRows.length?'Confira os dados reconhecidos antes de importar.':'Nenhuma transação foi reconhecida.',!importRows.length);}catch(error){clearImport();status(error.message||'Não foi possível ler o PDF.',true);}finally{busy=false;controls();}});
forms.import.addEventListener('submit',async event=>{event.preventDefault();if(!importFile)return;const items=[...$('#card-import-items').children].flatMap(tr=>{const controls=tr.querySelectorAll('input,select'),[check,date,name,value,group,payment,current,count]=controls;if(!check.checked)return[];return[{id:crypto.randomUUID(),page:importRows[Number(tr.dataset.index)].page,row:importRows[Number(tr.dataset.index)].row,purchaseDate:date.value,name:name.value,value:Number(value.value),groupId:group.value,payment:Number(payment.value),currentInstallment:Number(current.value),installmentCount:Number(count.value),confidence:importRows[Number(tr.dataset.index)].confidence}];});if(!items.length){status('Selecione ao menos uma transação.',true);return;}if(items.some(item=>!item.groupId)){status('Selecione o grupo de todas as transações marcadas.',true);return;}status('Calculando a identificação do arquivo…');const action={type:'import',id:crypto.randomUUID(),periodId:forms.import.elements.periodId.value,fileName:importFile.name,fileHash:await fileSha256(importFile),items};if(await request(action)){clearImport();view('expenses');status(`${items.length} transação(ões) importada(s) com sucesso.`);}});
function defaults(){const now=new Date();const today=todayInSaoPaulo(now);forms.transaction.elements.transactionDate.value=today;forms.period.elements.month.value=Number(today.slice(5,7));forms.period.elements.year.value=today.slice(0,4);installmentFields();}
months.forEach((name,index)=>forms.period.elements.month.add(new Option(name,index+1)));defaults();view('expenses');controls();
