import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { addMonthsClamped, expandInstallments, validateCreditAction } from '../credit-card-model.mjs';
import { handleCreditCard } from '../credit-card-api.mjs';
import { inferPurchaseDate, parseOcrText, validateImportAction } from '../credit-card-import-model.mjs';
const importMigration=readFileSync(new URL('../migrations/0011_credit_card_import.sql',import.meta.url),'utf8');
const editMigration=readFileSync(new URL('../migrations/0010_credit_card_edit.sql',import.meta.url),'utf8');
const migration=readFileSync(new URL('../migrations/0009_credit_card.sql',import.meta.url),'utf8');
function database(){const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');sql.exec(migration);sql.exec(editMigration);sql.exec(importMigration);const prepare=query=>{let args=[];const statement=sql.prepare(query);return{isWrite:/^\s*(INSERT|UPDATE|DELETE)/i.test(query),bind(...values){args=values;return this},async first(){return statement.get(...args)||null},async run(){return{meta:{changes:statement.run(...args).changes}}},async all(){return{results:statement.all(...args)}}}};return{sql,prepare,async batch(statements){sql.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(statement.isWrite?await statement.run():await statement.all());sql.exec('COMMIT');return result}catch(error){sql.exec('ROLLBACK');throw error}}};}
const req=body=>new Request('https://x/api/admin/credit-card',{method:body?'POST':'GET',headers:{'x-admin-password':'pw','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
const env=()=>({ADMIN_PASSWORD:'pw',CONTENT_DB:database()});
const id=()=>crypto.randomUUID();
test('grupo valida 30 caracteres e período valida datas',()=>{assert.equal(validateCreditAction({type:'group',id:id(),name:' SAÚDE '}).name,'SAÚDE');assert.throws(()=>validateCreditAction({type:'group',id:id(),name:'x'.repeat(31)}));assert.throws(()=>validateCreditAction({type:'period',id:id(),month:2,year:2026,startDate:'2026-02-30',endDate:'2026-03-01'}));assert.throws(()=>validateCreditAction({type:'period',id:id(),month:2,year:2026,startDate:'2026-03-02',endDate:'2026-03-01'}));});
test('parcela 5 de 10 gera a atual e as próximas cinco, ajustando fim do mês',()=>{const rows=expandInstallments({type:'transaction',id:id(),transactionDate:'2026-01-31',name:'Compra',value:12.34,groupId:id(),payment:2,currentInstallment:5,installmentCount:10});assert.deepEqual(rows.map(x=>x.installmentNumber),[5,6,7,8,9,10]);assert.deepEqual(rows.map(x=>x.transactionDate),['2026-01-31','2026-02-28','2026-03-31','2026-04-30','2026-05-31','2026-06-30']);assert.equal(new Set(rows.map(x=>x.seriesId)).size,1);});
test('à vista sempre usa parcela 1/1 e regras parceladas são validadas',()=>{const action=validateCreditAction({type:'transaction',id:id(),transactionDate:'2026-01-01',name:'Compra',value:10,groupId:id(),payment:1,currentInstallment:99,installmentCount:99});assert.equal(action.currentInstallment,1);assert.equal(action.installmentCount,1);for(const values of [{payment:3},{payment:2,currentInstallment:0,installmentCount:10},{payment:2,currentInstallment:11,installmentCount:10},{payment:2,currentInstallment:1,installmentCount:1000},{value:1.001}])assert.throws(()=>validateCreditAction({type:'transaction',id:id(),transactionDate:'2026-01-01',name:'Compra',value:10,groupId:id(),payment:2,currentInstallment:1,installmentCount:10,...values}));assert.equal(addMonthsClamped('2024-01-31',1),'2024-02-29');});
test('API encaixa parcelas em períodos existentes e períodos futuros',async()=>{const e=env();const group={type:'group',id:id(),name:'SAÚDE'};await handleCreditCard(req(group),e);const jan={type:'period',id:id(),month:1,year:2026,startDate:'2026-01-01',endDate:'2026-01-31'};await handleCreditCard(req(jan),e);const series={type:'transaction',id:id(),transactionDate:'2026-01-15',name:'Tratamento',value:100,groupId:group.id,payment:2,currentInstallment:5,installmentCount:6};let response=await handleCreditCard(req(series),e);assert.equal(response.status,200);let data=await response.json();assert.equal(data.transactions.length,2);assert.equal(data.transactions[0].periodId,null);assert.equal(data.transactions[1].periodId,jan.id);const feb={type:'period',id:id(),month:2,year:2026,startDate:'2026-02-01',endDate:'2026-02-28'};data=await(await handleCreditCard(req(feb),e)).json();assert.equal(data.transactions.find(x=>x.transactionDate==='2026-02-15').periodId,feb.id);});
test('repetir um envio parcelado não duplica parcelas',async()=>{const e=env();const group={type:'group',id:id(),name:'EDUCAÇÃO'};await handleCreditCard(req(group),e);const series={type:'transaction',id:id(),transactionDate:'2026-01-15',name:'Curso',value:50,groupId:group.id,payment:2,currentInstallment:5,installmentCount:10};assert.equal((await handleCreditCard(req(series),e)).status,200);assert.equal((await handleCreditCard(req(series),e)).status,409);const data=await(await handleCreditCard(req(),e)).json();assert.equal(data.transactions.length,6);assert.deepEqual(data.transactions.map(x=>x.installmentNumber).sort((a,b)=>a-b),[5,6,7,8,9,10]);});
test('impede período sobreposto, mês duplicado e grupo duplicado sem apagar dados',async()=>{const e=env();const p={type:'period',id:id(),month:1,year:2026,startDate:'2025-12-20',endDate:'2026-01-20'};assert.equal((await handleCreditCard(req(p),e)).status,200);assert.equal((await handleCreditCard(req({...p,id:id(),month:2,startDate:'2026-01-20',endDate:'2026-02-20'}),e)).status,409);assert.equal((await handleCreditCard(req({...p,id:id(),startDate:'2026-01-21',endDate:'2026-01-30'}),e)).status,409);const g={type:'group',id:id(),name:'SAÚDE'};await handleCreditCard(req(g),e);assert.equal((await handleCreditCard(req({...g,id:id(),name:'saúde'}),e)).status,409);});
test('banco preserva integridade e exige autenticação',async()=>{const e=env();assert.equal((await handleCreditCard(new Request('https://x/api/admin/credit-card'),e)).status,401);assert.throws(()=>e.CONTENT_DB.sql.exec("INSERT INTO credit_card_transactions (id,series_id,transaction_date,name,value,group_id,payment,installment_number,installment_count) VALUES ('x','x','2026-01-01','X',10,'missing',1,1,1)"));});
test('edita grupo com revisão, mantém ID e atualiza o combo das transações',async()=>{const e=env();const group={type:'group',id:id(),name:'SAÚDE'};let data=await(await handleCreditCard(req(group),e)).json();const saved=data.groups[0];let response=await handleCreditCard(req({type:'group',operation:'update',id:saved.id,revision:saved.revision,name:'BEM-ESTAR'}),e);assert.equal(response.status,200);data=await response.json();assert.equal(data.groups[0].id,saved.id);assert.equal(data.groups[0].name,'BEM-ESTAR');assert.equal(data.groups[0].revision,1);assert.equal((await handleCreditCard(req({type:'group',operation:'update',id:saved.id,revision:0,name:'ANTIGO'}),e)).status,409);});
test('editar período reencaixa e desencaixa transações pelas novas datas',async()=>{const e=env();const group={type:'group',id:id(),name:'CASA'};await handleCreditCard(req(group),e);const jan={type:'period',id:id(),month:1,year:2026,startDate:'2026-01-01',endDate:'2026-01-31'};let data=await(await handleCreditCard(req(jan),e)).json();await handleCreditCard(req({type:'transaction',id:id(),transactionDate:'2026-01-15',name:'Compra',value:10,groupId:group.id,payment:1}),e);data=await(await handleCreditCard(req(),e)).json();assert.equal(data.transactions[0].periodId,jan.id);const period=data.periods[0];data=await(await handleCreditCard(req({...period,type:'period',operation:'update',startDate:'2026-01-20',endDate:'2026-02-19'}),e)).json();assert.equal(data.transactions[0].periodId,null);assert.equal(data.periods[0].revision,1);assert.equal((await handleCreditCard(req({...period,type:'period',operation:'update'}),e)).status,409);});
test('edição de período impede sobreposição e preserva períodos em caso de erro',async()=>{const e=env();for(const p of [{type:'period',id:id(),month:1,year:2026,startDate:'2026-01-01',endDate:'2026-01-31'},{type:'period',id:id(),month:2,year:2026,startDate:'2026-02-01',endDate:'2026-02-28'}])await handleCreditCard(req(p),e);let data=await(await handleCreditCard(req(),e)).json();const feb=data.periods.find(x=>x.month===2);const response=await handleCreditCard(req({...feb,type:'period',operation:'update',startDate:'2026-01-15'}),e);assert.equal(response.status,409);data=await(await handleCreditCard(req(),e)).json();assert.equal(data.periods.find(x=>x.month===2).startDate,'2026-02-01');});
test('migração 0010 preserva grupos, períodos e transações existentes',()=>{const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');sql.exec(migration);sql.exec("INSERT INTO credit_card_groups(id,name,name_key) VALUES('g','SAÚDE','saúde')");sql.exec("INSERT INTO credit_card_periods(id,month,year,start_date,end_date) VALUES('p',1,2026,'2026-01-01','2026-01-31')");sql.exec("INSERT INTO credit_card_transactions(id,series_id,transaction_date,name,value,group_id,payment,installment_number,installment_count) VALUES('t','t','2026-01-10','X',10,'g',1,1,1)");sql.exec(editMigration);assert.equal(sql.prepare('SELECT revision FROM credit_card_groups').get().revision,0);assert.equal(sql.prepare('SELECT revision FROM credit_card_periods').get().revision,0);assert.equal(sql.prepare('SELECT period_id FROM credit_card_transactions').get().period_id,'p');assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);});

test('OCR interpreta compras, parcelas, ruídos e ignora pagamentos/créditos',()=>{const text=`Restaurantes\n005/08 | CAFE CENTRAL FLORIANOPOLIS BR R$ 114,89\nCompras parceladas\n18/12] CLINICA PARC 08/12 FLORIANOPOLIS BR R$ | 29000\nPagamentos/Créditos\n19/08] DESCONTO ANUIDADE R$ -45,50`;const rows=parseOcrText(text,{page:2,periodEnd:'2026-08-21',confidence:88});assert.equal(rows.length,3);assert.deepEqual(rows.map(x=>[x.purchaseDate,x.value,x.payment,x.currentInstallment,x.installmentCount,x.include]),[['2026-08-05',114.89,1,1,1,true],['2025-12-18',290,2,8,12,true],['2026-08-19',45.5,1,1,1,false]]);assert.equal(inferPurchaseDate('31/12','2026-08-21'),'2025-12-31');});

test('validação da importação exige hash, grupo e valores positivos',()=>{const base={type:'import',id:id(),periodId:id(),fileHash:'a'.repeat(64),fileName:'fatura.pdf',items:[{id:id(),page:2,row:1,purchaseDate:'2026-07-24',name:'Compra',value:10,groupId:id(),payment:1,currentInstallment:1,installmentCount:1,confidence:90}]};assert.equal(validateImportAction(base).items[0].name,'Compra');assert.throws(()=>validateImportAction({...base,fileHash:'x'}));assert.throws(()=>validateImportAction({...base,items:[{...base.items[0],value:-1}]}));});

test('importa PDF, cria projeções e confirma a parcela futura sem duplicar',async()=>{const e=env(),group={type:'group',id:id(),name:'SAÚDE'},aug={type:'period',id:id(),month:8,year:2026,startDate:'2026-07-22',endDate:'2026-08-21'},sep={type:'period',id:id(),month:9,year:2026,startDate:'2026-08-22',endDate:'2026-09-21'};await handleCreditCard(req(group),e);await handleCreditCard(req(aug),e);await handleCreditCard(req(sep),e);const item={id:id(),page:2,row:1,purchaseDate:'2025-12-18',name:'CLINICA PARC 08/12',value:290,groupId:group.id,payment:2,currentInstallment:8,installmentCount:12,confidence:91};let response=await handleCreditCard(req({type:'import',id:id(),periodId:aug.id,fileHash:'a'.repeat(64),fileName:'agosto.pdf',items:[item]}),e);assert.equal(response.status,200);let data=await response.json();assert.equal(data.transactions.length,5);assert.equal(data.transactions.find(x=>x.installmentNumber===8).periodId,aug.id);assert.equal(data.transactions.find(x=>x.installmentNumber===9).isProjected,1);response=await handleCreditCard(req({type:'import',id:id(),periodId:sep.id,fileHash:'b'.repeat(64),fileName:'setembro.pdf',items:[{...item,id:id(),row:2,name:'CLINICA PARC 09/12',currentInstallment:9}]}),e);assert.equal(response.status,200);data=await response.json();assert.equal(data.transactions.length,5);assert.equal(data.transactions.find(x=>x.installmentNumber===9).isProjected,0);assert.equal(data.transactions.find(x=>x.installmentNumber===9).periodId,sep.id);assert.equal((await handleCreditCard(req({type:'import',id:id(),periodId:sep.id,fileHash:'b'.repeat(64),fileName:'copia.pdf',items:[{...item,id:id()}]}),e)).status,409);});
