import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { addMonthsClamped, expandInstallments, validateCreditAction } from '../credit-card-model.mjs';
import { handleCreditCard } from '../credit-card-api.mjs';
import { inferPurchaseDate, parseOcrText, validateImportAction } from '../credit-card-import-model.mjs';
const importMigration=readFileSync(new URL('../migrations/0011_credit_card_import.sql',import.meta.url),'utf8');
const transactionEditMigration=readFileSync(new URL('../migrations/0012_credit_card_transaction_edit.sql',import.meta.url),'utf8');
const futurePeriodsMigration=readFileSync(new URL('../migrations/0013_credit_card_future_periods.sql',import.meta.url),'utf8');
const installmentCompetenceMigration=readFileSync(new URL('../migrations/0014_credit_card_installment_competence.sql',import.meta.url),'utf8');
const duplicateProjectionMigration=readFileSync(new URL('../migrations/0015_credit_card_remove_duplicate_projections.sql',import.meta.url),'utf8');
const editMigration=readFileSync(new URL('../migrations/0010_credit_card_edit.sql',import.meta.url),'utf8');
const migration=readFileSync(new URL('../migrations/0009_credit_card.sql',import.meta.url),'utf8');
function database(){const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');sql.exec(migration);sql.exec(editMigration);sql.exec(importMigration);sql.exec(transactionEditMigration);sql.exec(futurePeriodsMigration);sql.exec(installmentCompetenceMigration);const prepare=query=>{let args=[];const statement=sql.prepare(query);return{isWrite:/^\s*(INSERT|UPDATE|DELETE)/i.test(query),bind(...values){args=values;return this},async first(){return statement.get(...args)||null},async run(){return{meta:{changes:statement.run(...args).changes}}},async all(){return{results:statement.all(...args)}}}};return{sql,prepare,async batch(statements){sql.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(statement.isWrite?await statement.run():await statement.all());sql.exec('COMMIT');return result}catch(error){sql.exec('ROLLBACK');throw error}}};}
const req=body=>new Request('https://x/api/admin/credit-card',{method:body?'POST':'GET',headers:{'x-admin-password':'pw','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
const env=()=>({ADMIN_PASSWORD:'pw',CONTENT_DB:database()});
const id=()=>crypto.randomUUID();
test('grupo valida 30 caracteres e período valida datas',()=>{assert.equal(validateCreditAction({type:'group',id:id(),name:' SAÚDE '}).name,'SAÚDE');assert.throws(()=>validateCreditAction({type:'group',id:id(),name:'x'.repeat(31)}));assert.throws(()=>validateCreditAction({type:'period',id:id(),month:2,year:2026,startDate:'2026-02-30',endDate:'2026-03-01'}));assert.throws(()=>validateCreditAction({type:'period',id:id(),month:2,year:2026,startDate:'2026-03-02',endDate:'2026-03-01'}));});
test('nome da transação aceita até 50 caracteres',()=>{const base={type:'transaction',id:id(),transactionDate:'2026-08-01',name:'x'.repeat(50),value:1,groupId:id(),payment:1};assert.equal(validateCreditAction(base).name.length,50);assert.throws(()=>validateCreditAction({...base,name:'x'.repeat(51)}));});
test('parcela 5 de 10 gera a atual e as próximas cinco, ajustando fim do mês',()=>{const rows=expandInstallments({type:'transaction',id:id(),transactionDate:'2026-01-31',name:'Compra',value:12.34,groupId:id(),payment:2,currentInstallment:5,installmentCount:10});assert.deepEqual(rows.map(x=>x.installmentNumber),[5,6,7,8,9,10]);assert.deepEqual(rows.map(x=>x.transactionDate),['2026-01-31','2026-02-28','2026-03-31','2026-04-30','2026-05-31','2026-06-30']);assert.equal(new Set(rows.map(x=>x.seriesId)).size,1);});
test('à vista sempre usa parcela 1/1 e regras parceladas são validadas',()=>{const action=validateCreditAction({type:'transaction',id:id(),transactionDate:'2026-01-01',name:'Compra',value:10,groupId:id(),payment:1,currentInstallment:99,installmentCount:99});assert.equal(action.currentInstallment,1);assert.equal(action.installmentCount,1);for(const values of [{payment:3},{payment:2,currentInstallment:0,installmentCount:10},{payment:2,currentInstallment:11,installmentCount:10},{payment:2,currentInstallment:1,installmentCount:1000},{value:1.001}])assert.throws(()=>validateCreditAction({type:'transaction',id:id(),transactionDate:'2026-01-01',name:'Compra',value:10,groupId:id(),payment:2,currentInstallment:1,installmentCount:10,...values}));assert.equal(addMonthsClamped('2024-01-31',1),'2024-02-29');});
test('API encaixa parcelas em períodos existentes e períodos futuros',async()=>{const e=env();const group={type:'group',id:id(),name:'SAÚDE'};await handleCreditCard(req(group),e);const jan={type:'period',id:id(),month:1,year:2026,startDate:'2026-01-01',endDate:'2026-01-31'};await handleCreditCard(req(jan),e);const series={type:'transaction',id:id(),transactionDate:'2026-01-15',name:'Tratamento',value:100,groupId:group.id,payment:2,currentInstallment:5,installmentCount:6};let response=await handleCreditCard(req(series),e);assert.equal(response.status,200);let data=await response.json();assert.equal(data.transactions.length,2);assert.equal(data.transactions[0].periodId,null);assert.equal(data.transactions[1].periodId,jan.id);const feb={type:'period',id:id(),month:2,year:2026,startDate:'2026-02-01',endDate:'2026-02-28'};data=await(await handleCreditCard(req(feb),e)).json();assert.equal(data.transactions.find(x=>x.transactionDate==='2026-02-15').periodId,feb.id);});
test('repetir um envio parcelado não duplica parcelas',async()=>{const e=env();const group={type:'group',id:id(),name:'EDUCAÇÃO'};await handleCreditCard(req(group),e);const series={type:'transaction',id:id(),transactionDate:'2026-01-15',name:'Curso',value:50,groupId:group.id,payment:2,currentInstallment:5,installmentCount:10};assert.equal((await handleCreditCard(req(series),e)).status,200);assert.equal((await handleCreditCard(req(series),e)).status,409);const data=await(await handleCreditCard(req(),e)).json();assert.equal(data.transactions.length,6);assert.deepEqual(data.transactions.map(x=>x.installmentNumber).sort((a,b)=>a-b),[5,6,7,8,9,10]);});
test('impede período sobreposto, mês duplicado e grupo duplicado sem apagar dados',async()=>{const e=env();const p={type:'period',id:id(),month:1,year:2026,startDate:'2025-12-20',endDate:'2026-01-20'};assert.equal((await handleCreditCard(req(p),e)).status,200);assert.equal((await handleCreditCard(req({...p,id:id(),month:2,startDate:'2026-01-20',endDate:'2026-02-20'}),e)).status,409);assert.equal((await handleCreditCard(req({...p,id:id(),startDate:'2026-01-21',endDate:'2026-01-30'}),e)).status,409);const g={type:'group',id:id(),name:'SAÚDE'};await handleCreditCard(req(g),e);assert.equal((await handleCreditCard(req({...g,id:id(),name:'saúde'}),e)).status,409);});
test('banco preserva integridade e exige autenticação',async()=>{const e=env();assert.equal((await handleCreditCard(new Request('https://x/api/admin/credit-card'),e)).status,401);assert.throws(()=>e.CONTENT_DB.sql.exec("INSERT INTO credit_card_transactions (id,series_id,transaction_date,name,value,group_id,payment,installment_number,installment_count) VALUES ('x','x','2026-01-01','X',10,'missing',1,1,1)"));});
test('edita grupo com revisão, mantém ID e atualiza o combo das transações',async()=>{const e=env();const group={type:'group',id:id(),name:'SAÚDE'};let data=await(await handleCreditCard(req(group),e)).json();const saved=data.groups[0];let response=await handleCreditCard(req({type:'group',operation:'update',id:saved.id,revision:saved.revision,name:'BEM-ESTAR'}),e);assert.equal(response.status,200);data=await response.json();assert.equal(data.groups[0].id,saved.id);assert.equal(data.groups[0].name,'BEM-ESTAR');assert.equal(data.groups[0].revision,1);assert.equal((await handleCreditCard(req({type:'group',operation:'update',id:saved.id,revision:0,name:'ANTIGO'}),e)).status,409);});
test('editar período reencaixa e desencaixa transações pelas novas datas',async()=>{const e=env();const group={type:'group',id:id(),name:'CASA'};await handleCreditCard(req(group),e);const jan={type:'period',id:id(),month:1,year:2026,startDate:'2026-01-01',endDate:'2026-01-31'};let data=await(await handleCreditCard(req(jan),e)).json();await handleCreditCard(req({type:'transaction',id:id(),transactionDate:'2026-01-15',name:'Compra',value:10,groupId:group.id,payment:1}),e);data=await(await handleCreditCard(req(),e)).json();assert.equal(data.transactions[0].periodId,jan.id);const period=data.periods[0];data=await(await handleCreditCard(req({...period,type:'period',operation:'update',startDate:'2026-01-20',endDate:'2026-02-19'}),e)).json();assert.equal(data.transactions[0].periodId,null);assert.equal(data.periods[0].revision,1);assert.equal((await handleCreditCard(req({...period,type:'period',operation:'update'}),e)).status,409);});
test('edição de período impede sobreposição e preserva períodos em caso de erro',async()=>{const e=env();for(const p of [{type:'period',id:id(),month:1,year:2026,startDate:'2026-01-01',endDate:'2026-01-31'},{type:'period',id:id(),month:2,year:2026,startDate:'2026-02-01',endDate:'2026-02-28'}])await handleCreditCard(req(p),e);let data=await(await handleCreditCard(req(),e)).json();const feb=data.periods.find(x=>x.month===2);const response=await handleCreditCard(req({...feb,type:'period',operation:'update',startDate:'2026-01-15'}),e);assert.equal(response.status,409);data=await(await handleCreditCard(req(),e)).json();assert.equal(data.periods.find(x=>x.month===2).startDate,'2026-02-01');});
test('migração 0010 preserva grupos, períodos e transações existentes',()=>{const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');sql.exec(migration);sql.exec("INSERT INTO credit_card_groups(id,name,name_key) VALUES('g','SAÚDE','saúde')");sql.exec("INSERT INTO credit_card_periods(id,month,year,start_date,end_date) VALUES('p',1,2026,'2026-01-01','2026-01-31')");sql.exec("INSERT INTO credit_card_transactions(id,series_id,transaction_date,name,value,group_id,payment,installment_number,installment_count) VALUES('t','t','2026-01-10','X',10,'g',1,1,1)");sql.exec(editMigration);assert.equal(sql.prepare('SELECT revision FROM credit_card_groups').get().revision,0);assert.equal(sql.prepare('SELECT revision FROM credit_card_periods').get().revision,0);assert.equal(sql.prepare('SELECT period_id FROM credit_card_transactions').get().period_id,'p');assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);});

test('OCR interpreta compras, parcelas, ruídos e ignora pagamentos/créditos',()=>{const text=`Restaurantes\n005/08 | CAFE CENTRAL FLORIANOPOLIS BR R$ 114,89\nCompras parceladas\n18/12] CLINICA PARC 08/12 FLORIANOPOLIS BR R$ | 29000\nPagamentos/Créditos\n19/08] DESCONTO ANUIDADE R$ -45,50`;const rows=parseOcrText(text,{page:2,periodEnd:'2026-08-21',confidence:88});assert.equal(rows.length,3);assert.deepEqual(rows.map(x=>[x.purchaseDate,x.value,x.payment,x.currentInstallment,x.installmentCount,x.include]),[['2026-08-05',114.89,1,1,1,true],['2025-12-18',290,2,8,12,true],['2026-08-19',45.5,1,1,1,false]]);assert.equal(inferPurchaseDate('31/12','2026-08-21'),'2025-12-31');});

test('OCR importa a seção Lançamentos em processamento mesmo com valores negativos',()=>{const text=`Pagamentos/Créditos\n19/09 PAGAMENTO FATURA R$ -100,00\nLançamentos em processamento\n20/09 COMPRA PENDENTE R$ -45,90\n20/09 CURSO PARC 02/06 R$ -120,00`;const rows=parseOcrText(text,{page:2,periodEnd:'2026-09-21',confidence:90});assert.deepEqual(rows.map(x=>[x.name,x.value,x.include,x.payment,x.currentInstallment,x.installmentCount]),[['PAGAMENTO FATURA',100,false,1,1,1],['COMPRA PENDENTE',45.9,true,1,1,1],['CURSO PARC 02/06',120,true,2,2,6]]);});

test('OCR marca compras em processamento mesmo quando não lê o cabeçalho',()=>{const text=`Pagamentos/Créditos\n19/09 PAGAMENTO FATURA R$ 100,00\n20/09 DL UBER RIDES SAO PAULO BR R$ 20,99\n20/09 APPLE.COM/BILL SAO PAULO R$ 2,00`;const rows=parseOcrText(text,{page:2,periodEnd:'2026-09-21',confidence:80});assert.deepEqual(rows.map(x=>[x.name,x.include]),[['PAGAMENTO FATURA',false],['DL UBER RIDES SAO PAULO BR',true],['APPLE.COM/BILL SAO PAULO',true]]);});

test('validação da importação exige hash, grupo e valores positivos',()=>{const base={type:'import',id:id(),periodId:id(),fileHash:'a'.repeat(64),fileName:'fatura.pdf',items:[{id:id(),page:2,row:1,purchaseDate:'2026-07-24',name:'Compra',value:10,groupId:id(),payment:1,currentInstallment:1,installmentCount:1,confidence:90}]};assert.equal(validateImportAction(base).items[0].name,'Compra');assert.throws(()=>validateImportAction({...base,fileHash:'x'}));assert.throws(()=>validateImportAction({...base,items:[{...base.items[0],value:-1}]}));});

test('importa PDF, cria projeções e permite substituir o mesmo arquivo na mesma fatura',async()=>{const e=env(),group={type:'group',id:id(),name:'SAÚDE'},aug={type:'period',id:id(),month:8,year:2026,startDate:'2026-07-22',endDate:'2026-08-21'},sep={type:'period',id:id(),month:9,year:2026,startDate:'2026-08-22',endDate:'2026-09-21'};await handleCreditCard(req(group),e);await handleCreditCard(req(aug),e);await handleCreditCard(req(sep),e);const item={id:id(),page:2,row:1,purchaseDate:'2025-12-18',name:'CLINICA PARC 08/12',value:290,groupId:group.id,payment:2,currentInstallment:8,installmentCount:12,confidence:91};let response=await handleCreditCard(req({type:'import',id:id(),periodId:aug.id,fileHash:'a'.repeat(64),fileName:'agosto.pdf',items:[item]}),e);assert.equal(response.status,200);let data=await response.json();assert.equal(data.transactions.length,5);assert.equal(data.transactions.find(x=>x.installmentNumber===8).periodId,aug.id);assert.equal(data.transactions.find(x=>x.installmentNumber===9).isProjected,1);const septemberItem={...item,id:id(),row:2,name:'CLINICA PARC 09/12',currentInstallment:9};assert.equal((await handleCreditCard(req({type:'import',id:id(),periodId:sep.id,fileHash:'a'.repeat(64),fileName:'fatura-errada.pdf',items:[septemberItem]}),e)).status,409);response=await handleCreditCard(req({type:'import',id:id(),periodId:sep.id,fileHash:'b'.repeat(64),fileName:'setembro.pdf',items:[septemberItem]}),e);assert.equal(response.status,200);data=await response.json();assert.equal(data.transactions.length,5);assert.equal(data.transactions.find(x=>x.installmentNumber===9).isProjected,0);assert.equal(data.transactions.find(x=>x.installmentNumber===9).periodId,sep.id);response=await handleCreditCard(req({type:'import',id:id(),periodId:sep.id,fileHash:'b'.repeat(64),fileName:'copia.pdf',items:[{...septemberItem,id:id(),row:3}]}),e);assert.equal(response.status,200);data=await response.json();assert.equal(data.transactions.filter(x=>x.installmentNumber===9).length,1);assert.equal(data.imports.filter(x=>x.periodId===sep.id).length,1);});

test('concilia parcela prevista quando o OCR altera levemente o nome',async()=>{const e=env(),group={type:'group',id:id(),name:'UTILIDADES'},sep={type:'period',id:id(),month:9,year:2026,startDate:'2026-07-23',endDate:'2026-08-20'},oct={type:'period',id:id(),month:10,year:2026,startDate:'2026-08-21',endDate:'2026-09-21'};await handleCreditCard(req(group),e);await handleCreditCard(req(sep),e);await handleCreditCard(req(oct),e);const first={id:id(),page:1,row:1,purchaseDate:'2026-01-21',name:'AMAZONMKTPLC PARC 07/09 SAO PAULO BR',value:52.22,groupId:group.id,payment:2,currentInstallment:7,installmentCount:9,confidence:90};let data=await(await handleCreditCard(req({type:'import',id:id(),periodId:sep.id,fileHash:'1'.repeat(64),fileName:'setembro.pdf',items:[first]}),e)).json();assert.equal(data.transactions.filter(x=>x.installmentNumber===8).length,1);const current={...first,id:id(),row:2,name:'AMAZONMKTPLC PARC 08/09 SAO PAULO BR I',currentInstallment:8};data=await(await handleCreditCard(req({type:'import',id:id(),periodId:oct.id,fileHash:'2'.repeat(64),fileName:'outubro.pdf',items:[current]}),e)).json();const installment=data.transactions.filter(x=>x.installmentNumber===8);assert.equal(installment.length,1);assert.equal(installment[0].isProjected,0);assert.equal(installment[0].periodId,oct.id);});

test('importação substitui a fatura e pagamentos a prazo posteriores de forma atômica',async()=>{const e=env(),group={type:'group',id:id(),name:'TESTE'},oct={type:'period',id:id(),month:10,year:2026,startDate:'2026-08-21',endDate:'2026-09-21'},nov={type:'period',id:id(),month:11,year:2026,startDate:'2026-09-22',endDate:'2026-10-20'};await handleCreditCard(req(group),e);await handleCreditCard(req(oct),e);await handleCreditCard(req(nov),e);for(const [name,transactionDate,payment,currentInstallment] of [['ANTIGA OUTUBRO','2026-09-01',1,1],['ANTIGA PRAZO NOVEMBRO','2026-10-01',2,2],['VISTA NOVEMBRO','2026-10-02',1,1]])await handleCreditCard(req({type:'transaction',id:id(),transactionDate,name,value:10,groupId:group.id,payment,currentInstallment,installmentCount:currentInstallment}),e);const item={id:id(),page:1,row:1,purchaseDate:'2026-09-10',name:'NOVA PARC 01/02',value:25,groupId:group.id,payment:2,currentInstallment:1,installmentCount:2,confidence:90};const data=await(await handleCreditCard(req({type:'import',id:id(),periodId:oct.id,fileHash:'3'.repeat(64),fileName:'outubro.pdf',items:[item]}),e)).json();assert.equal(data.transactions.some(row=>row.name==='ANTIGA OUTUBRO'),false);assert.equal(data.transactions.some(row=>row.name==='ANTIGA PRAZO NOVEMBRO'),false);assert.equal(data.transactions.filter(row=>row.name==='NOVA PARC 01/02').length,2);assert.equal(data.transactions.some(row=>row.name==='VISTA NOVEMBRO'),true);});

test('lista por inclusão, edita e exclui logicamente uma transação',async()=>{const e=env(),group={type:'group',id:id(),name:'CASA'};await handleCreditCard(req(group),e);const transaction={type:'transaction',id:id(),transactionDate:'2026-08-10',name:'Compra',value:20,groupId:group.id,payment:1};let data=await(await handleCreditCard(req(transaction),e)).json();let saved=data.transactions[0];assert.equal(saved.revision,0);data=await(await handleCreditCard(req({...transaction,operation:'update',id:saved.id,revision:saved.revision,name:'Compra corrigida',value:25}),e)).json();saved=data.transactions[0];assert.equal(saved.name,'Compra corrigida');assert.equal(saved.value,25);assert.equal(saved.revision,1);assert.equal((await handleCreditCard(req({...transaction,operation:'update',id:saved.id,revision:0}),e)).status,409);data=await(await handleCreditCard(req({type:'transaction',operation:'delete',id:saved.id,revision:saved.revision}),e)).json();assert.equal(data.transactions.length,0);assert.ok(e.CONTENT_DB.sql.prepare('SELECT deleted_at FROM credit_card_transactions WHERE id=?').get(saved.id).deleted_at);});

test('excluir transação importada preserva o histórico da importação',async()=>{const e=env(),group={type:'group',id:id(),name:'SAÚDE'},period={type:'period',id:id(),month:8,year:2026,startDate:'2026-07-22',endDate:'2026-08-21'};await handleCreditCard(req(group),e);await handleCreditCard(req(period),e);const item={id:id(),page:2,row:1,purchaseDate:'2026-08-10',name:'FARMÁCIA',value:50,groupId:group.id,payment:1,currentInstallment:1,installmentCount:1,confidence:90};let data=await(await handleCreditCard(req({type:'import',id:id(),periodId:period.id,fileHash:'c'.repeat(64),fileName:'fatura.pdf',items:[item]}),e)).json();const saved=data.transactions[0];data=await(await handleCreditCard(req({type:'transaction',operation:'delete',id:saved.id,revision:saved.revision}),e)).json();assert.equal(data.transactions.length,0);assert.equal(e.CONTENT_DB.sql.prepare('SELECT count(*) AS total FROM credit_card_import_items').get().total,1);});

test('migração 0012 preserva transações existentes e inicializa a auditoria',()=>{const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');sql.exec(migration);sql.exec(editMigration);sql.exec(importMigration);sql.exec("INSERT INTO credit_card_groups(id,name,name_key) VALUES('g','CASA','casa')");sql.exec("INSERT INTO credit_card_transactions(id,series_id,transaction_date,name,value,group_id,payment,installment_number,installment_count) VALUES('t','t','2026-08-10','Compra',20,'g',1,1,1)");const created=sql.prepare("SELECT created_at FROM credit_card_transactions WHERE id='t'").get().created_at;sql.exec(transactionEditMigration);const row=sql.prepare("SELECT revision,updated_at,deleted_at FROM credit_card_transactions WHERE id='t'").get();assert.equal(row.revision,0);assert.equal(row.updated_at,created);assert.equal(row.deleted_at,null);assert.equal(sql.prepare('PRAGMA foreign_key_check').all().length,0);});

test('excluir tudo remove transações visíveis e preserva cadastros auxiliares',async()=>{const e=env(),group={type:'group',id:id(),name:'TESTE'},period={type:'period',id:id(),month:8,year:2026,startDate:'2026-08-01',endDate:'2026-08-31'};await handleCreditCard(req(group),e);await handleCreditCard(req(period),e);for(const name of ['A','B'])await handleCreditCard(req({type:'transaction',id:id(),transactionDate:'2026-08-10',name,value:10,groupId:group.id,payment:1}),e);let data=await(await handleCreditCard(req(),e)).json();assert.equal(data.transactions.length,2);data=await(await handleCreditCard(req({type:'transaction',operation:'delete-all',id:id()}),e)).json();assert.equal(data.transactions.length,0);assert.equal(data.groups.length,1);assert.equal(data.periods.length,1);assert.equal(e.CONTENT_DB.sql.prepare('SELECT count(*) AS total FROM credit_card_transactions WHERE deleted_at IS NOT NULL').get().total,2);});

test('exclui período selecionado e somente pagamentos a prazo posteriores',async()=>{const e=env(),group={type:'group',id:id(),name:'TESTE'},sep={type:'period',id:id(),month:9,year:2026,startDate:'2026-07-23',endDate:'2026-08-20'},oct={type:'period',id:id(),month:10,year:2026,startDate:'2026-08-21',endDate:'2026-09-21'},nov={type:'period',id:id(),month:11,year:2026,startDate:'2026-09-22',endDate:'2026-10-20'};await handleCreditCard(req(group),e);for(const period of [sep,oct,nov])await handleCreditCard(req(period),e);const rows=[['SETEMBRO PRAZO','2026-08-01',2,2],['OUTUBRO VISTA','2026-09-01',1,1],['OUTUBRO PRAZO','2026-09-02',2,2],['NOVEMBRO VISTA','2026-10-01',1,1],['NOVEMBRO PRAZO','2026-10-02',2,3]];for(const [name,transactionDate,payment,currentInstallment] of rows)await handleCreditCard(req({type:'transaction',id:id(),transactionDate,name,value:10,groupId:group.id,payment,currentInstallment,installmentCount:currentInstallment}),e);const response=await handleCreditCard(req({type:'transaction',operation:'delete-period-forward',id:id(),periodId:oct.id}),e);assert.equal(response.status,200);const data=await response.json();assert.deepEqual(data.transactions.map(item=>item.name).sort(),['NOVEMBRO VISTA','SETEMBRO PRAZO']);});

test('parcela importada entra na próxima fatura pela competência mesmo com fechamento variável',async()=>{const e=env(),group={type:'group',id:id(),name:'TESTE'},aug={type:'period',id:id(),month:8,year:2026,startDate:'2026-07-23',endDate:'2026-08-22'};await handleCreditCard(req(group),e);await handleCreditCard(req(aug),e);const item={id:id(),page:2,row:1,purchaseDate:'2026-08-10',name:'CURSO PARC 01/02',value:100,groupId:group.id,payment:2,currentInstallment:1,installmentCount:2,confidence:90};let data=await(await handleCreditCard(req({type:'import',id:id(),periodId:aug.id,fileHash:'d'.repeat(64),fileName:'agosto.pdf',items:[item]}),e)).json();const future=data.transactions.find(x=>x.installmentNumber===2);assert.equal(future.periodId,null);const sep={type:'period',id:id(),month:9,year:2026,startDate:'2026-08-23',endDate:'2026-09-20'};data=await(await handleCreditCard(req(sep),e)).json();assert.equal(data.transactions.find(x=>x.installmentNumber===2).periodId,sep.id);});

test('parcela futura usa a competência quando a próxima fatura já existe',async()=>{const e=env(),group={type:'group',id:id(),name:'TESTE'},sep={type:'period',id:id(),month:9,year:2026,startDate:'2026-07-23',endDate:'2026-08-20'},oct={type:'period',id:id(),month:10,year:2026,startDate:'2026-08-21',endDate:'2026-09-21'},nov={type:'period',id:id(),month:11,year:2026,startDate:'2026-09-22',endDate:'2026-10-20'};await handleCreditCard(req(group),e);await handleCreditCard(req(sep),e);await handleCreditCard(req(oct),e);await handleCreditCard(req(nov),e);const item={id:id(),page:2,row:1,purchaseDate:'2026-08-15',name:'COMPRA PARC 01/03',value:42,groupId:group.id,payment:2,currentInstallment:1,installmentCount:3,confidence:90};const data=await(await handleCreditCard(req({type:'import',id:id(),periodId:sep.id,fileHash:'e'.repeat(64),fileName:'setembro.pdf',items:[item]}),e)).json();assert.equal(data.transactions.find(x=>x.installmentNumber===1).periodId,sep.id);assert.equal(data.transactions.find(x=>x.installmentNumber===2).periodId,oct.id);assert.equal(data.transactions.find(x=>x.installmentNumber===3).periodId,nov.id);});

test('migração 0015 remove previsão duplicada e o restante futuro da série antiga',()=>{const db=database(),sql=db.sql;sql.exec("INSERT INTO credit_card_groups(id,name,name_key) VALUES('g','UTILIDADES','utilidades')");sql.exec("INSERT INTO credit_card_periods(id,month,year,start_date,end_date) VALUES('oct',10,2026,'2026-08-21','2026-09-21'),('nov',11,2026,'2026-09-22','2026-10-20')");sql.exec(`INSERT INTO credit_card_transactions(id,series_id,transaction_date,name,value,group_id,payment,installment_number,installment_count,period_id) VALUES
('confirmed','new','2026-09-21','AMAZON PARC 08/09 SAO PAULO BR I',52.22,'g',2,8,9,'oct'),
('duplicate','old','2026-09-01','AMAZON PARC 07/09 SAO PAULO BR',52.22,'g',2,8,9,'oct'),
('old-future','old','2026-10-01','AMAZON PARC 07/09 SAO PAULO BR',52.22,'g',2,9,9,'nov'),
('different-value','other','2026-09-01','AMAZON PARC 07/09 SAO PAULO BR',51.22,'g',2,8,9,'oct')`);sql.exec(`INSERT INTO credit_card_transaction_meta(transaction_id,purchase_date,source_series_key,is_projected,billing_month,billing_year) VALUES
('confirmed','2026-01-21','new-key',0,10,2026),
('duplicate','2026-01-21','old-key',1,10,2026),
('old-future','2026-01-21','old-key',1,11,2026),
('different-value','2026-01-21','other-key',1,10,2026)`);sql.exec(duplicateProjectionMigration);const rows=Object.fromEntries(sql.prepare('SELECT id,deleted_at FROM credit_card_transactions').all().map(row=>[row.id,row.deleted_at]));assert.equal(rows.confirmed,null);assert.ok(rows.duplicate);assert.ok(rows['old-future']);assert.equal(rows['different-value'],null);});
