import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { validateMonthlyExpenseAction } from '../monthly-expenses-model.mjs';
import { handleMonthlyExpenses } from '../monthly-expenses-api.mjs';
const migration=readFileSync(new URL('../migrations/0024_monthly_expenses.sql',import.meta.url),'utf8');
const incomeMigration=readFileSync(new URL('../migrations/0025_monthly_income.sql',import.meta.url),'utf8');
const settlementMigration=readFileSync(new URL('../migrations/0026_monthly_expense_settlement.sql',import.meta.url),'utf8');
const incomePeriodMigration=readFileSync(new URL('../migrations/0027_monthly_income_period.sql',import.meta.url),'utf8');
const entrySettlementMigration=readFileSync(new URL('../migrations/0028_monthly_entry_settlement.sql',import.meta.url),'utf8');
const disregardMigration=readFileSync(new URL('../migrations/0029_monthly_entry_disregarded.sql',import.meta.url),'utf8');
const paymentDayMigration=readFileSync(new URL('../migrations/0030_monthly_expense_payment_day.sql',import.meta.url),'utf8');
const id=()=>crypto.randomUUID();
function database(){const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');sql.exec(migration);sql.exec(incomeMigration);sql.exec(settlementMigration);sql.exec(incomePeriodMigration);sql.exec(entrySettlementMigration);sql.exec(disregardMigration);sql.exec(paymentDayMigration);const prepare=query=>{let args=[];const statement=sql.prepare(query);return{bind(...values){args=values;return this},async first(){return statement.get(...args)||null},async run(){const result=statement.run(...args);return{meta:{changes:result.changes}}},async all(){return{results:statement.all(...args)}}}};return{sql,prepare,async batch(statements){sql.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(/^\s*(SELECT|WITH)/i.test(statement.source||'')?await statement.all():await statement.run());sql.exec('COMMIT');return results;}catch(error){sql.exec('ROLLBACK');throw error;}}};}
// D1 statements do not expose their SQL; this wrapper supports the SELECTs used by overview.
function env(){const db=database(),original=db.prepare;db.prepare=query=>{const statement=original(query);statement.source=query;return statement;};return{ADMIN_PASSWORD:'pw',ALLOW_LEGACY_ADMIN_AUTH:'true',CONTENT_DB:db};}
const request=body=>new Request('https://x/api/admin/monthly-expenses',{method:body?'POST':'GET',headers:{'x-admin-password':'pw','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});

test('valida proprietário, valor, período e identificadores',()=>{const groupId=id();assert.equal(validateMonthlyExpenseAction({type:'expense',paymentDay:10,id:id(),owner:'Ale',name:'Internet',value:99.9,groupId}).value,99.9);assert.throws(()=>validateMonthlyExpenseAction({type:'expense',paymentDay:10,id:id(),owner:'Outro',name:'X',value:1,groupId}));assert.throws(()=>validateMonthlyExpenseAction({type:'month',month:13,year:2026,expenseIds:[]}));assert.throws(()=>validateMonthlyExpenseAction({type:'income',id:id(),owner:'Ale',name:'Salário',value:5000,month:13,year:2026}));});

test('cadastra grupos e gastos e atualiza a seleção de cada mês',async()=>{const e=env(),groupId=id(),expenseId=id();assert.equal((await handleMonthlyExpenses(request({type:'group',id:groupId,name:'CASA'}),e)).status,200);assert.equal((await handleMonthlyExpenses(request({type:'expense',paymentDay:10,id:expenseId,owner:'Ana',name:'Internet',value:120.5,groupId}),e)).status,200);let response=await handleMonthlyExpenses(request({type:'month',month:9,year:2026,expenseIds:[expenseId]}),e);assert.equal(response.status,200);let data=await response.json();assert.deepEqual(data.entries,[{expenseId,month:9,year:2026,settled:0,disregarded:0}]);response=await handleMonthlyExpenses(request({type:'month',month:9,year:2026,expenseIds:[]}),e);data=await response.json();assert.equal(data.entries.length,0);assert.equal(data.expenses[0].groupName,'CASA');});

test('API exige autenticação',async()=>{const e=env();const response=await handleMonthlyExpenses(new Request('https://x/api/admin/monthly-expenses'),e);assert.equal(response.status,401);});

test('cadastra renda mensal por proprietário e competência',async()=>{const e=env(),incomeId=id();const response=await handleMonthlyExpenses(request({type:'income',id:incomeId,owner:'Ale',name:'Salário',value:5000,month:9,year:2026}),e);assert.equal(response.status,200);const data=await response.json();assert.deepEqual(data.incomes,[{id:incomeId,owner:'Ale',name:'Salário',value:5000,month:9,year:2026,revision:0}]);});

test('exclui todos os gastos e suas competências sem excluir grupos',async()=>{const e=env(),groupId=id(),expenseId=id();await handleMonthlyExpenses(request({type:'group',id:groupId,name:'CASA'}),e);await handleMonthlyExpenses(request({type:'expense',paymentDay:10,id:expenseId,owner:'Ale',name:'Condomínio',value:500,groupId}),e);await handleMonthlyExpenses(request({type:'month',month:9,year:2026,expenseIds:[expenseId]}),e);const response=await handleMonthlyExpenses(request({type:'delete-all-expenses'}),e),data=await response.json();assert.equal(response.status,200);assert.equal(data.expenses.length,0);assert.equal(data.entries.length,0);assert.equal(data.groups.length,1);});

test('exclui todas as rendas sem alterar gastos',async()=>{const e=env(),groupId=id();await handleMonthlyExpenses(request({type:'group',id:groupId,name:'CASA'}),e);await handleMonthlyExpenses(request({type:'expense',paymentDay:10,id:id(),owner:'Ana',name:'Luz',value:100,groupId}),e);await handleMonthlyExpenses(request({type:'income',id:id(),owner:'Ana',name:'Salário',value:5000,month:9,year:2026}),e);const data=await(await handleMonthlyExpenses(request({type:'delete-all-incomes'}),e)).json();assert.equal(data.incomes.length,0);assert.equal(data.expenses.length,1);});

test('persiste dia de pagamento e liquidação por competência',async()=>{const e=env(),groupId=id(),expenseId=id();await handleMonthlyExpenses(request({type:'group',id:groupId,name:'SAÚDE'}),e);let response=await handleMonthlyExpenses(request({type:'expense',paymentDay:13,id:expenseId,owner:'Ana',name:'Plano',value:300,groupId}),e),data=await response.json();assert.equal(response.status,200);assert.equal(data.expenses[0].paymentDay,13);response=await handleMonthlyExpenses(request({type:'settlement',expenseId,month:9,year:2026,settled:true}),e);data=await response.json();assert.equal(response.status,200);assert.deepEqual(data.entries,[{expenseId,month:9,year:2026,settled:1,disregarded:0}]);response=await handleMonthlyExpenses(request({type:'settlement',expenseId,month:9,year:2026,settled:false}),e);data=await response.json();assert.equal(data.entries[0].settled,0);assert.throws(()=>validateMonthlyExpenseAction({type:'expense',paymentDay:32,id:id(),owner:'Ale',name:'X',value:1,groupId}));});


test('desconsidera e reconsidera um gasto somente na competência selecionada',async()=>{const e=env(),groupId=id(),expenseId=id();await handleMonthlyExpenses(request({type:'group',id:groupId,name:'CASA'}),e);await handleMonthlyExpenses(request({type:'expense',paymentDay:10,id:expenseId,owner:'Ale',name:'Internet',value:100,groupId}),e);let data=await(await handleMonthlyExpenses(request({type:'consideration',expenseId,month:9,year:2026,disregarded:true}),e)).json();assert.equal(data.entries[0].disregarded,1);data=await(await handleMonthlyExpenses(request({type:'consideration',expenseId,month:9,year:2026,disregarded:false}),e)).json();assert.equal(data.entries[0].disregarded,0);});

test('salvar o mês associa os gastos e seus estados somente à competência escolhida',async()=>{const e=env(),groupId=id(),first=id(),second=id();await handleMonthlyExpenses(request({type:'group',id:groupId,name:'CASA'}),e);await handleMonthlyExpenses(request({type:'expense',paymentDay:10,id:first,owner:'Ale',name:'Internet',value:100,groupId}),e);await handleMonthlyExpenses(request({type:'expense',paymentDay:10,id:second,owner:'Ana',name:'Luz',value:200,groupId}),e);const data=await(await handleMonthlyExpenses(request({type:'month',month:10,year:2026,entries:[{expenseId:first,settled:true,disregarded:false},{expenseId:second,settled:false,disregarded:true}]}),e)).json();const byId=new Map(data.entries.map(item=>[item.expenseId,item]));assert.deepEqual(byId.get(first),{expenseId:first,month:10,year:2026,settled:1,disregarded:0});assert.deepEqual(byId.get(second),{expenseId:second,month:10,year:2026,settled:0,disregarded:1});});

test('edita e exclui gastos, rendas e grupos com controle de revisão',async()=>{const e=env(),groupId=id(),expenseId=id(),incomeId=id();let data=await(await handleMonthlyExpenses(request({type:'group',id:groupId,name:'CASA'}),e)).json();await handleMonthlyExpenses(request({type:'expense',paymentDay:10,id:expenseId,owner:'Ale',name:'Luz',value:100,groupId}),e);await handleMonthlyExpenses(request({type:'income',id:incomeId,owner:'Ale',name:'Salário',value:5000,month:9,year:2026}),e);data=await(await handleMonthlyExpenses(request({type:'expense',paymentDay:15,operation:'update',id:expenseId,revision:0,owner:'Ana',name:'Energia',value:120,groupId}),e)).json();assert.equal(data.expenses[0].name,'Energia');assert.equal(data.expenses[0].paymentDay,15);assert.equal(data.expenses[0].revision,1);assert.equal((await handleMonthlyExpenses(request({type:'expense',paymentDay:10,operation:'delete',id:expenseId,revision:0}),e)).status,409);data=await(await handleMonthlyExpenses(request({type:'expense',paymentDay:10,operation:'delete',id:expenseId,revision:1}),e)).json();assert.equal(data.expenses.length,0);data=await(await handleMonthlyExpenses(request({type:'income',operation:'update',id:incomeId,revision:0,owner:'Ana',name:'Renda',value:5100,month:10,year:2026}),e)).json();assert.equal(data.incomes[0].revision,1);assert.equal(data.incomes[0].month,10);data=await(await handleMonthlyExpenses(request({type:'income',operation:'delete',id:incomeId,revision:1}),e)).json();assert.equal(data.incomes.length,0);data=await(await handleMonthlyExpenses(request({type:'group',operation:'update',id:groupId,revision:0,name:'MORADIA'}),e)).json();assert.equal(data.groups[0].name,'MORADIA');data=await(await handleMonthlyExpenses(request({type:'group',operation:'delete',id:groupId,revision:1}),e)).json();assert.equal(data.groups.length,0);});
